#!/bin/bash

set -xeuo pipefail

# Set PIXI_HOME to the *parent* directory of the desired "bin" directory because the
# install.sh script automatically appends "/bin" to the PIXI_HOME value.
wget -qO- https://pixi.sh/install.sh | PIXI_HOME="${CONDA_DIR}" PIXI_NO_PATH_UPDATE=1 bash

# Install AWS CLI
wget -qO- https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip >awscliv2.zip
unzip -q awscliv2.zip
aws/install --install-dir "${CONDA_DIR}/share/aws-cli" --bin-dir "${CONDA_DIR}/bin"
rm -rf awscliv2.zip aws/
